int pulsador = A0;   
const int ledCount = 9;

int ledPins[] = {
  2, 3, 4, 5, 6, 7, 8, 9, 10
}; 

void setup() {
    for (int thisLed = 0; thisLed < ledCount; thisLed++) {
    pinMode(ledPins[thisLed], OUTPUT);
  }
}

void loop() {
  
//  int sensorReading = analogRead(analogPin);
  int avionesneg = 8;

/*  for(int aviones; aviones<4; aviones++){
      digitalWrite(ledPins[aviones], HIGH);
      digitalWrite(ledPins[avionesneg], HIGH);
      delay(160);
      digitalWrite(ledPins[aviones], LOW);
      digitalWrite(ledPins[avionesneg], LOW);
      avionesneg = avionesneg-1;
      if( avionesneg = 4)
        avionesneg = 8;
  }*/

    
/*    digitalWrite(ledPins[0], HIGH);
    digitalWrite(ledPins[1], HIGH);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], LOW);
    digitalWrite(ledPins[2], LOW);
    delay(160);
     digitalWrite(ledPins[0], HIGH);
    digitalWrite(ledPins[1], HIGH);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], LOW);
    digitalWrite(ledPins[2], LOW);
    delay(160);
     digitalWrite(ledPins[0], HIGH);
    digitalWrite(ledPins[1], HIGH);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], LOW);
    digitalWrite(ledPins[2], LOW);
    delay(160);
    digitalWrite(ledPins[0], HIGH);
    digitalWrite(ledPins[1], HIGH);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], LOW);
    digitalWrite(ledPins[2], LOW);
    delay(160);
     digitalWrite(ledPins[0], HIGH);
    digitalWrite(ledPins[1], HIGH);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], LOW);
    digitalWrite(ledPins[2], LOW);
    //+++++++++++++++++++++++++++++++++++++++++++++++*/
    //++++++++++++++++++++++++++++++++++++++++++++++
    digitalWrite(ledPins[0], HIGH);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[1], HIGH);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[2], LOW);
    delay(160);
    digitalWrite(ledPins[1], LOW);
    delay(160);
    //++++++++++++++++++++++++++++++++++++++++++++++
      digitalWrite(ledPins[0], HIGH);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[1], HIGH);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[2], LOW);
    delay(160);
    digitalWrite(ledPins[1], LOW);
    delay(160);
    //++++++++++++++++++++++++++++++++++++++++++++++
      digitalWrite(ledPins[0], HIGH);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[1], HIGH);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[2], LOW);
    delay(160);
    digitalWrite(ledPins[1], LOW);
    delay(160);
    //++++++++++++++++++++++++++++++++++++++++++++++
      digitalWrite(ledPins[0], HIGH);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[1], HIGH);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[2], LOW);
    delay(160);
    digitalWrite(ledPins[1], LOW);
    delay(160);
    //++++++++++++++++++++++++++++++++++++++++++++++
      digitalWrite(ledPins[0], HIGH);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[1], HIGH);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[2], LOW);
    delay(160);
    digitalWrite(ledPins[1], LOW);
    delay(160);
    //++++++++++++++++++++++++++++++++++++++++++++++
    /*//++++++++++++++++++++++++++++++++++++++++++++++
    digitalWrite(ledPins[0], HIGH);
    digitalWrite(ledPins[1], HIGH);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], LOW);
    digitalWrite(ledPins[2], LOW);
    delay(160);
     digitalWrite(ledPins[0], HIGH);
    digitalWrite(ledPins[1], HIGH);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], LOW);
    digitalWrite(ledPins[2], LOW);
    delay(160);
     digitalWrite(ledPins[0], HIGH);
    digitalWrite(ledPins[1], HIGH);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], LOW);
    digitalWrite(ledPins[2], LOW);
    delay(160);
    digitalWrite(ledPins[0], HIGH);
    digitalWrite(ledPins[1], HIGH);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], LOW);
    digitalWrite(ledPins[2], LOW);
    delay(160);
     digitalWrite(ledPins[0], HIGH);
    digitalWrite(ledPins[1], HIGH);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], LOW);
    digitalWrite(ledPins[2], LOW);
    delay(160);
    //++++++++++++++++++++++++++++++++++++++++++++++*/
    //++++++++++++++++++++++++++++++++++++++++++++++
    digitalWrite(ledPins[0], HIGH);
    delay(160);
    digitalWrite(ledPins[0],LOW);
    digitalWrite(ledPins[1], HIGH);
    delay(160);
    digitalWrite(ledPins[1],LOW);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[2],LOW);
     delay(160);
    //++++++++++++++++++++++++++++++++++++++++++++++
    digitalWrite(ledPins[0], HIGH);
    delay(160);
    digitalWrite(ledPins[0],LOW);
    digitalWrite(ledPins[1], HIGH);
    delay(160);
    digitalWrite(ledPins[1],LOW);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[2],LOW);
     delay(160);
     //++++++++++++++++++++++++++++++++++++++++++++++
    digitalWrite(ledPins[0], HIGH);
    delay(160);
    digitalWrite(ledPins[0],LOW);
    digitalWrite(ledPins[1], HIGH);
    delay(160);
    digitalWrite(ledPins[1],LOW);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[2],LOW);
     delay(160);
     //++++++++++++++++++++++++++++++++++++++++++++++
    digitalWrite(ledPins[0], HIGH);
    delay(160);
    digitalWrite(ledPins[0],LOW);
    digitalWrite(ledPins[1], HIGH);
    delay(160);
    digitalWrite(ledPins[1],LOW);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[2],LOW);
    delay(160);
    //++++++++++++++++++++++++++++++++++++++++++++++
    digitalWrite(ledPins[0], HIGH);
    delay(160);
    digitalWrite(ledPins[0],LOW);
    digitalWrite(ledPins[1], HIGH);
    delay(160);
    digitalWrite(ledPins[1],LOW);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[2],LOW);
    delay(160);
    //++++++++++++++++++++++++++++++++++++++++++++++
    /*//++++++++++++++++++++++++++++++++++++++++++++++
    digitalWrite(ledPins[0], HIGH);
    digitalWrite(ledPins[1], HIGH);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], LOW);
    digitalWrite(ledPins[2], LOW);
    delay(160);
     digitalWrite(ledPins[0], HIGH);
    digitalWrite(ledPins[1], HIGH);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], LOW);
    digitalWrite(ledPins[2], LOW);
    delay(160);
     digitalWrite(ledPins[0], HIGH);
    digitalWrite(ledPins[1], HIGH);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], LOW);
    digitalWrite(ledPins[2], LOW);
    delay(160);
    digitalWrite(ledPins[0], HIGH);
    digitalWrite(ledPins[1], HIGH);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], LOW);
    digitalWrite(ledPins[2], LOW);
    delay(160);
     digitalWrite(ledPins[0], HIGH);
    digitalWrite(ledPins[1], HIGH);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], LOW);
    digitalWrite(ledPins[2], LOW);
    delay(160);
    //++++++++++++++++++++++++++++++++++++++++++++++*/
    //++++++++++++++++++++++++++++++++++++++++++++++
    digitalWrite(ledPins[0], HIGH);
    delay(160);
    digitalWrite(ledPins[0],LOW);
    digitalWrite(ledPins[1], HIGH);
    delay(160);
    digitalWrite(ledPins[1],LOW);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[2],LOW);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[2],LOW);
    digitalWrite(ledPins[1], HIGH);
    delay(160);
    digitalWrite(ledPins[1],LOW);
    digitalWrite(ledPins[0], HIGH);
    delay(160);
    digitalWrite(ledPins[0],LOW);
    delay(160);
    //++++++++++++++++++++++++++++++++++++++++++++++
        digitalWrite(ledPins[0], HIGH);
    delay(160);
    digitalWrite(ledPins[0],LOW);
    digitalWrite(ledPins[1], HIGH);
    delay(160);
    digitalWrite(ledPins[1],LOW);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[2],LOW);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[2],LOW);
    digitalWrite(ledPins[1], HIGH);
    delay(160);
    digitalWrite(ledPins[1],LOW);
    digitalWrite(ledPins[0], HIGH);
    delay(160);
    digitalWrite(ledPins[0],LOW);
    delay(160);
    //++++++++++++++++++++++++++++++++++++++++++++++
        digitalWrite(ledPins[0], HIGH);
    delay(160);
    digitalWrite(ledPins[0],LOW);
    digitalWrite(ledPins[1], HIGH);
    delay(160);
    digitalWrite(ledPins[1],LOW);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[2],LOW);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[2],LOW);
    digitalWrite(ledPins[1], HIGH);
    delay(160);
    digitalWrite(ledPins[1],LOW);
    digitalWrite(ledPins[0], HIGH);
    delay(160);
    digitalWrite(ledPins[0],LOW);
    delay(160);
    //++++++++++++++++++++++++++++++++++++++++++++++
        digitalWrite(ledPins[0], HIGH);
    delay(160);
    digitalWrite(ledPins[0],LOW);
    digitalWrite(ledPins[1], HIGH);
    delay(160);
    digitalWrite(ledPins[1],LOW);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[2],LOW);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[2],LOW);
    digitalWrite(ledPins[1], HIGH);
    delay(160);
    digitalWrite(ledPins[1],LOW);
    digitalWrite(ledPins[0], HIGH);
    delay(160);
    digitalWrite(ledPins[0],LOW);
    delay(160);
    //++++++++++++++++++++++++++++++++++++++++++++++
        digitalWrite(ledPins[0], HIGH);
    delay(160);
    digitalWrite(ledPins[0],LOW);
    digitalWrite(ledPins[1], HIGH);
    delay(160);
    digitalWrite(ledPins[1],LOW);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[2],LOW);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[2],LOW);
    digitalWrite(ledPins[1], HIGH);
    delay(160);
    digitalWrite(ledPins[1],LOW);
    digitalWrite(ledPins[0], HIGH);
    delay(160);
    digitalWrite(ledPins[0],LOW);
    delay(160);
    //++++++++++++++++++++++++++++++++++++++++++++++
    /*//++++++++++++++++++++++++++++++++++++++++++++++
    digitalWrite(ledPins[0], HIGH);
    digitalWrite(ledPins[1], HIGH);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], LOW);
    digitalWrite(ledPins[2], LOW);
    delay(160);
     digitalWrite(ledPins[0], HIGH);
    digitalWrite(ledPins[1], HIGH);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], LOW);
    digitalWrite(ledPins[2], LOW);
    delay(160);
     digitalWrite(ledPins[0], HIGH);
    digitalWrite(ledPins[1], HIGH);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], LOW);
    digitalWrite(ledPins[2], LOW);
    delay(160);
    digitalWrite(ledPins[0], HIGH);
    digitalWrite(ledPins[1], HIGH);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], LOW);
    digitalWrite(ledPins[2], LOW);
    delay(160);
     digitalWrite(ledPins[0], HIGH);
    digitalWrite(ledPins[1], HIGH);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], LOW);
    digitalWrite(ledPins[2], LOW);
    //++++++++++++++++++++++++++++++++++++++++++++++
    //++++++++++++++++++++++++++++++++++++++++++++++*/
    digitalWrite(ledPins[0], HIGH);
    delay(160);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], HIGH);
    delay(160);
    digitalWrite(ledPins[1], LOW);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[0], HIGH);
    delay(160);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], HIGH);
    delay(160);
    digitalWrite(ledPins[0], HIGH);
    delay(160);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], LOW);
    digitalWrite(ledPins[2], LOW);
    delay(160); 
    //++++++++++++++++++++++++++++++++++++++++++++++
    digitalWrite(ledPins[0], HIGH);
    delay(160);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], HIGH);
    delay(160);
    digitalWrite(ledPins[1], LOW);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[0], HIGH);
    delay(160);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], HIGH);
    delay(160);
    digitalWrite(ledPins[0], HIGH);
    delay(160);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], LOW);
    digitalWrite(ledPins[2], LOW);
    delay(160); 
    //++++++++++++++++++++++++++++++++++++++++++++++
     digitalWrite(ledPins[0], HIGH);
    delay(160);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], HIGH);
    delay(160);
    digitalWrite(ledPins[1], LOW);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[0], HIGH);
    delay(160);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], HIGH);
    delay(160);
    digitalWrite(ledPins[0], HIGH);
    delay(160);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], LOW);
    digitalWrite(ledPins[2], LOW);
    delay(160); 
    //++++++++++++++++++++++++++++++++++++++++++++++
     digitalWrite(ledPins[0], HIGH);
    delay(160);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], HIGH);
    delay(160);
    digitalWrite(ledPins[1], LOW);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[0], HIGH);
    delay(160);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], HIGH);
    delay(160);
    digitalWrite(ledPins[0], HIGH);
    delay(160);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], LOW);
    digitalWrite(ledPins[2], LOW);
    delay(160); 
    //++++++++++++++++++++++++++++++++++++++++++++++
     digitalWrite(ledPins[0], HIGH);
    delay(160);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], HIGH);
    delay(160);
    digitalWrite(ledPins[1], LOW);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[0], HIGH);
    delay(160);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], HIGH);
    delay(160);
    digitalWrite(ledPins[0], HIGH);
    delay(160);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], LOW);
    digitalWrite(ledPins[2], LOW);
    delay(160); 
    //++++++++++++++++++++++++++++++++++++++++++++++
    //++++++++++++++++++++++++++++++++++++++++++++++
    digitalWrite(ledPins[0], HIGH);
    digitalWrite(ledPins[1], HIGH);
    digitalWrite(ledPins[2], HIGH);
    delay(200);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], LOW);
    digitalWrite(ledPins[2], LOW);
    delay(200);
     digitalWrite(ledPins[0], HIGH);
    digitalWrite(ledPins[1], HIGH);
    digitalWrite(ledPins[2], HIGH);
    delay(200);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], LOW);
    digitalWrite(ledPins[2], LOW);
    delay(200);
     digitalWrite(ledPins[0], HIGH);
    digitalWrite(ledPins[1], HIGH);
    digitalWrite(ledPins[2], HIGH);
    delay(200);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], LOW);
    digitalWrite(ledPins[2], LOW);
    delay(200);
    digitalWrite(ledPins[0], HIGH);
    digitalWrite(ledPins[1], HIGH);
    digitalWrite(ledPins[2], HIGH);
    delay(200);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], LOW);
    digitalWrite(ledPins[2], LOW);
    delay(200);
     digitalWrite(ledPins[0], HIGH);
    digitalWrite(ledPins[1], HIGH);
    digitalWrite(ledPins[2], HIGH);
    delay(200);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], LOW);
    digitalWrite(ledPins[2], LOW);
    //++++++++++++++++++++++++++++++++++++++++++++++
    //++++++++++++++++++++++++++++++++++++++++++++++
    digitalWrite(ledPins[0], HIGH);
    delay(160);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], HIGH);
    delay(160);
    digitalWrite(ledPins[1], LOW);
    digitalWrite(ledPins[2], HIGH);
    delay(160);    
    digitalWrite(ledPins[0], HIGH);
    delay(160);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], HIGH);
    delay(160);
    digitalWrite(ledPins[0], HIGH);
    delay(200);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], HIGH);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], LOW);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], LOW);
    digitalWrite(ledPins[2], LOW);
    delay(200);
    //++++++++++++++++++++++++++++++++++++++++++++++
    digitalWrite(ledPins[0], HIGH);
    delay(160);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], HIGH);
    delay(160);
    digitalWrite(ledPins[1], LOW);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[0], HIGH);
    delay(160);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], HIGH);
    delay(160);
    digitalWrite(ledPins[0], HIGH);
    delay(200);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], HIGH);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], LOW);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], LOW);
    digitalWrite(ledPins[2], LOW);
    delay(200);
    //++++++++++++++++++++++++++++++++++++++++++++++
    digitalWrite(ledPins[0], HIGH);
    delay(160);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], HIGH);
    delay(160);
    digitalWrite(ledPins[1], LOW);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[0], HIGH);
    delay(160);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], HIGH);
    delay(160);
    digitalWrite(ledPins[0], HIGH);
    delay(200);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], HIGH);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], LOW);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], LOW);
    digitalWrite(ledPins[2], LOW);
    delay(200);
    //++++++++++++++++++++++++++++++++++++++++++++++
    digitalWrite(ledPins[0], HIGH);
    delay(160);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], HIGH);
    delay(160);
    digitalWrite(ledPins[1], LOW);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[0], HIGH);
    delay(160);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], HIGH);
    delay(160);
    digitalWrite(ledPins[0], HIGH);
    delay(200);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], HIGH);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], LOW);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], LOW);
    digitalWrite(ledPins[2], LOW);
    delay(200);
    //++++++++++++++++++++++++++++++++++++++++++++++
    digitalWrite(ledPins[0], HIGH);
    delay(160);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], HIGH);
    delay(160);
    digitalWrite(ledPins[1], LOW);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[0], HIGH);
    delay(160);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], HIGH);
    delay(160);
    digitalWrite(ledPins[0], HIGH);
    delay(200);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], HIGH);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], LOW);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], LOW);
    digitalWrite(ledPins[2], LOW);
    delay(200);
     //++++++++++++++++++++++++++++++++++++++++++++++
    /*//++++++++++++++++++++++++++++++++++++++++++++++
    digitalWrite(ledPins[0], HIGH);
    digitalWrite(ledPins[1], HIGH);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], LOW);
    digitalWrite(ledPins[2], LOW);
    delay(160);
     digitalWrite(ledPins[0], HIGH);
    digitalWrite(ledPins[1], HIGH);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], LOW);
    digitalWrite(ledPins[2], LOW);
    delay(160);
     digitalWrite(ledPins[0], HIGH);
    digitalWrite(ledPins[1], HIGH);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], LOW);
    digitalWrite(ledPins[2], LOW);
    delay(160);
    digitalWrite(ledPins[0], HIGH);
    digitalWrite(ledPins[1], HIGH);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], LOW);
    digitalWrite(ledPins[2], LOW);
    delay(160);
     digitalWrite(ledPins[0], HIGH);
    digitalWrite(ledPins[1], HIGH);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[0], LOW);
    digitalWrite(ledPins[1], LOW);
    digitalWrite(ledPins[2], LOW);
    delay(160);
    //++++++++++++++++++++++++++++++++++++++++++++++
    //++++++++++++++++++++++++++++++++++++++++++++++*/
     digitalWrite(ledPins[0], HIGH);
    delay(100);
    digitalWrite(ledPins[0],LOW);
    delay(100);
    digitalWrite(ledPins[0], HIGH);
    delay(160);
    digitalWrite(ledPins[0],LOW);
    digitalWrite(ledPins[1], HIGH);
    delay(100);
    digitalWrite(ledPins[1],LOW);
    delay(100);
    digitalWrite(ledPins[1], HIGH);
    delay(160);
    digitalWrite(ledPins[1],LOW);
    digitalWrite(ledPins[2], HIGH);
    delay(100);
    digitalWrite(ledPins[2],LOW);
    delay(100);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[2],LOW);
    
    //++++++++++++++++++++++++++++++++++++++++++++++
     digitalWrite(ledPins[0], HIGH);
    delay(100);
    digitalWrite(ledPins[0],LOW);
    delay(100);
    digitalWrite(ledPins[0], HIGH);
    delay(160);
    digitalWrite(ledPins[0],LOW);
    digitalWrite(ledPins[1], HIGH);
    delay(100);
    digitalWrite(ledPins[1],LOW);
    delay(100);
    digitalWrite(ledPins[1], HIGH);
    delay(160);
    digitalWrite(ledPins[1],LOW);
    digitalWrite(ledPins[2], HIGH);
    delay(100);
    digitalWrite(ledPins[2],LOW);
    delay(100);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[2],LOW);
    
    //++++++++++++++++++++++++++++++++++++++++++++++
     digitalWrite(ledPins[0], HIGH);
    delay(100);
    digitalWrite(ledPins[0],LOW);
    delay(100);
    digitalWrite(ledPins[0], HIGH);
    delay(160);
    digitalWrite(ledPins[0],LOW);
    digitalWrite(ledPins[1], HIGH);
    delay(100);
    digitalWrite(ledPins[1],LOW);
    delay(100);
    digitalWrite(ledPins[1], HIGH);
    delay(160);
    digitalWrite(ledPins[1],LOW);
    digitalWrite(ledPins[2], HIGH);
    delay(100);
    digitalWrite(ledPins[2],LOW);
    delay(100);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[2],LOW);
    
    //++++++++++++++++++++++++++++++++++++++++++++++
     digitalWrite(ledPins[0], HIGH);
    delay(100);
    digitalWrite(ledPins[0],LOW);
    delay(100);
    digitalWrite(ledPins[0], HIGH);
    delay(160);
    digitalWrite(ledPins[0],LOW);
    digitalWrite(ledPins[1], HIGH);
    delay(100);
    digitalWrite(ledPins[1],LOW);
    delay(100);
    digitalWrite(ledPins[1], HIGH);
    delay(160);
    digitalWrite(ledPins[1],LOW);
    digitalWrite(ledPins[2], HIGH);
    delay(100);
    digitalWrite(ledPins[2],LOW);
    delay(100);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[2],LOW);
    
    //++++++++++++++++++++++++++++++++++++++++++++++
     digitalWrite(ledPins[0], HIGH);
    delay(100);
    digitalWrite(ledPins[0],LOW);
    delay(100);
    digitalWrite(ledPins[0], HIGH);
    delay(160);
    digitalWrite(ledPins[0],LOW);
    digitalWrite(ledPins[1], HIGH);
    delay(100);
    digitalWrite(ledPins[1],LOW);
    delay(100);
    digitalWrite(ledPins[1], HIGH);
    delay(160);
    digitalWrite(ledPins[1],LOW);
    digitalWrite(ledPins[2], HIGH);
    delay(100);
    digitalWrite(ledPins[2],LOW);
    delay(100);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[2],LOW);
    
    //++++++++++++++++++++++++++++++++++++++++++++++

     digitalWrite(ledPins[0], HIGH);
    delay(100);
    digitalWrite(ledPins[0],LOW);
    delay(100);
    digitalWrite(ledPins[0], HIGH);
    delay(160);
    digitalWrite(ledPins[0],LOW);
    digitalWrite(ledPins[1], HIGH);
    delay(100);
    digitalWrite(ledPins[1],LOW);
    delay(100);
    digitalWrite(ledPins[1], HIGH);
    delay(160);
    digitalWrite(ledPins[1],LOW);
    digitalWrite(ledPins[2], HIGH);
    delay(100);
    digitalWrite(ledPins[2],LOW);
    delay(100);
    digitalWrite(ledPins[2], HIGH);
    delay(160);
    digitalWrite(ledPins[2],LOW);
    
    //++++++++++++++++++++++++++++++++++++++++++++++


  }

